In [1]:
import cv2
import pandas as pd
import numpy as np

In [149]:
def rotate_x(theta_x):
    r1 = [1,0,0,0]
    r2 = [0, np.cos(theta_x), -np.sin(theta_x), 0]
    
    r3 = [0, np.sin(theta_x), np.cos(theta_x), 0]
    
    r4 = [0,0,0,1]
    return np.array([r1,r2,r3,r4])

def rotate_y(theta_y):
    r1 = [np.cos(theta_y), 0, np.sin(theta_y), 0]
    r2 = [0, 1, 0, 0]
    
    r3 = [-np.sin(theta_y),0, np.cos(theta_y), 0]
    
    r4 = [0,0,0,1]
    return np.array([r1,r2,r3,r4])

def rotate_z(theta_z):
    r1 = [np.cos(theta_z), -np.sin(theta_z), 0, 0]
    r2 = [np.sin(theta_z), np.cos(theta_z), 0, 0 ]
    
    r3 = [0, 0, 1, 0]
    
    r4 = [0, 0, 0, 1]
    return np.array([r1,r2,r3,r4])

def rotate(p, thetas=(0,0,0), degrees=False, transpose=False):
    """ rotate x, then y, then z"""
    if degrees == True:
        thetas = [np.deg2rad(th) for th in thetas]
    X_rot_mat = rotate_x(thetas[0])
    Y_rot_mat = rotate_y(thetas[1])
    Z_rot_mat = rotate_z(thetas[2])
    if transpose:
        X_rot_mat = X_rot_mat.T
        Y_rot_mat = Y_rot_mat.T
        Z_rot_mat = Z_rot_mat.T
        
    rot_mat = np.dot(np.dot(Z_rot_mat, Y_rot_mat), X_rot_mat)
    return np.dot(rot_mat, p), rot_mat

    #return np.dot(np.dot(np.dot(rotate_x(thetas[0]), rotate_y(thetas[1])), rotate_z(thetas[2])), p)

def CtoT(C):
    """C is camera position, will return translation matrix"""
    
    return np.vstack([np.hstack([np.identity(3), C.reshape(-1,1)]), np.array([0,0,0,1])])


In [18]:
np.array([1,1,0,1])*rotate_z(np.deg2rad(45))


array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [21]:
np.dot(rotate_y(np.deg2rad(45)), np.array([1,0,0,1]))


array([ 0.70710678,  0.        , -0.70710678,  1.        ])

In [121]:
p1, R = rotate(np.array([1,0,0,1]),thetas=(0,45, 45), degrees=True,transpose=False)

In [122]:
p1

array([ 0.5       ,  0.5       , -0.70710678,  1.        ])

In [123]:
R

array([[ 0.5       , -0.70710678,  0.5       ,  0.        ],
       [ 0.5       ,  0.70710678,  0.5       ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [150]:
C = np.array([0,0,5]) # position of camera

Tr = CtoT(C)
Tr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  5.],
       [ 0.,  0.,  0.,  1.]])

In [151]:
T = np.dot(R, Tr)

In [152]:
T

array([[ 0.5       , -0.70710678,  0.5       ,  2.5       ],
       [ 0.5       ,  0.70710678,  0.5       ,  2.5       ],
       [-0.70710678,  0.        ,  0.70710678,  3.53553391],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [153]:
np.dot(T,np.array([1,0,0,1]))

array([ 3.        ,  3.        ,  2.82842712,  1.        ])

In [154]:
p1

array([ 0.5       ,  0.5       , -0.70710678,  1.        ])

In [155]:
np.dot(Tr, p1)

array([ 0.5       ,  0.5       ,  4.29289322,  1.        ])

In [156]:
np.dot(Tr, np.array([1,0,0,1]))

array([ 1.,  0.,  5.,  1.])